spring:
  threads:
    virtual:
      enabled: true    

oinfaces:
  primefaces:
    theme: omega 
  faces:
    project-stage: development  
    facelets-libraries: /tags/tags.taglib.xml
  omnifaces:
    faces-views-enabled: true

tomcat:
  version: @tomcat.version@
jetty:
  version: @jetty.version@
undertow:
  version: @undertow.version@

application-users:
  users-credentials:
    - username: persapiens
      password: 123
      authorities: ROLE_ADMIN
    - username: nyilmaz
      password: qwe
      authorities: ROLE_USER

weld:
  dev-mode: true

omnifaces:
  socket-endpoint-enabled: true
  servlet-push-enabled: true
